default:
  image: docker:stable
services:
  - docker:dind
before_script:
  - apk update
  - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - docker-compose --version
    - make backend_build

deploy-job:
  stage: deploy
  script:
    - make backend_db run_app