stages:
  - build
  - deploy
build-job:
  stage: build
  script:
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    - docker-compose --version
    - make backend_build

deploy-job:
  stage: deploy
  script:
    - make backend_db run_app