default:
  image: docker:stable

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind
before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose
  - docker-compose --version
stages:
  - deploy
deploy-job:
  stage: deploy
  script:
    - make bootstrap