default:
  image: docker:stable
services:
  - docker:dind
before_script:
  - apk update
  - apk add curl
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - docker-compose --version
stages:
  - deploy
deploy-job:
  stage: deploy
  script:
    - make bootstrap