default:
  image: docker:stable

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind
before_script:
  - apk add --no-cache docker-compose
  - apk add --no-cache make
stages:
  - deploy
deploy-job:
  stage: deploy
  script:
    - make bootstrap