version: '3.7'
services:
  lambda: &lambda
    image: lambda:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HTTP_SERVER_PORT=3000
      - API_VERSION=1
      - MONGO_PREFIX=mongodb
      - MONGO_HOST=172.30.2.2
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=lambda
      - MONGO_DB_AUTH=admin
      - FIRST_ADMIN_PASSWORD=Admin@123
      - GRPC_SERVER_PORT=50050
      - USER_SERVICE_GRPC_HOST=127.0.0.1:50050
      - AUTH_SERVICE_GRPC_HOST=127.0.0.1:50050
    volumes:
      - "/var/lambda/storage"
    container_name: lambda-backend-1
    depends_on:
      - mongo
  gamma:
    <<: *lambda
    container_name: lambda-backend-1
    networks:
      lambda-network:
        ipv4_address: 172.30.6.2
  
  auth:
    image: lambda-auth:latest
    restart: always
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      - HTTP_SERVER_PORT=3001
      - API_VERSION=1
      - MONGO_PREFIX=mongodb
      - MONGO_HOST=172.30.2.2
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=lambda
      - MONGO_DB_AUTH=admin
      - FIRST_ADMIN_PASSWORD=Admin@123
      - GRPC_SERVER_PORT=50051
      - AUTH_SERVICE_GRPC_HOST=172.30.2.3:50051
      - USER_SERVICE_GRPC_HOST=172.30.2.4:50052
    container_name: lambda-auth-1
    networks:
      lambda-network:
        ipv4_address: 172.30.2.3

  user:
    image: lambda-user:latest
    restart: always
    ports:
      - "3002:3002"
      - "50052:50052"
    environment:
      - HTTP_SERVER_PORT=3002
      - API_VERSION=1
      - MONGO_PREFIX=mongodb
      - MONGO_HOST=172.30.2.2
      - MONGO_PORT=27017
      - MONGO_USER=admin
      - MONGO_PASSWORD=admin
      - MONGO_DB_NAME=lambda
      - MONGO_DB_AUTH=admin
      - FIRST_ADMIN_PASSWORD=Admin@123
      - GRPC_SERVER_PORT=50052
      - AUTH_SERVICE_GRPC_HOST=172.30.2.3:50051
      - USER_SERVICE_GRPC_HOST=172.30.2.4:50052
    container_name: lambda-user-1
    networks:
      lambda-network:
        ipv4_address: 172.30.2.4

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "/var/lambda/storage/mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: lambda
    container_name: lambda-mongo-1
    networks:
      lambda-network:
        ipv4_address: 172.30.2.2

networks:
  lambda-network:
    name: lambda-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16