version: '3.7'
services:
  lambda: &lambda
    image: lambda:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HTTP_SERVER_PORT=3000
      - API_VERSION=1
      - MONGO_PREFIX=mongodb
      - MONGO_HOST=172.30.2.2
      - MONGO_PORT=27017
      - MONGO_USER=
      - MONGO_PASSWORD=
      - MONGO_DB_NAME=lambda
      - MONGO_DB_AUTH=
      - FIRST_ADMIN_PASSWORD=
    volumes:
      - "/var/lambda/storage"
    container_name: lambda-backend-1
    depends_on:
      - mongo
  gamma:
    <<: *lambda
    container_name: lambda-backend-1
    networks:
      lambda-network:
        ipv4_address: 172.30.6.2
  
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - "/var/lambda/storage/mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: lambda
    container_name: lambda-mongo-1
    networks:
      lambda-network:
        ipv4_address: 172.30.2.2

networks:
  lambda-network:
    name: lambda-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16